[package]
name = "dark_droid"
version = "0.1.0"
edition = "2021"

[lints.clippy]
pedantic = "deny"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
